spring.application.name=interview-tracker
spring.config.import=optional:file:./config/application-local.properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.open-in-view=false
